infosolidario/config/routes.rb
Rails.application.routes.draw do

  get 'donaciones/index'

  get 'lista/index'

  get 'usuarios/index'

  get 'productos/index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :ongs
  devise_for :empresas
  devise_for :donantes

  get 'welcome/index'

  root 'welcome#index'

end

infosolidario/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

infosolidario/app/models/donacion_recurso.rb
class DonacionRecurso < ActiveRecord::Base
end

infosolidario/app/models/donacion_tiempo.rb
class DonacionTiempo < ActiveRecord::Base
end

infosolidario/app/models/donante.rb
class Donante < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

infosolidario/app/models/empresa.rb
class Empresa < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

infosolidario/app/models/ong.rb
class Ong < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

infosolidario/app/models/producto.rb
class Producto < ActiveRecord::Base
end

infosolidario/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

infosolidario/app/controllers/donaciones_controller.rb
class DonacionesController < ApplicationController
  def index
  	@recurso = DonacionRecurso.all
  	@tiempo = DonacionTiempo.all
  end
end

infosolidario/app/controllers/lista_controller.rb
class ListaController < ApplicationController
  def index
  	@lista = DonacionTiempo.all + DonacionRecurso.all
  end
end

infosolidario/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index
  	@lista = Producto.all
  end
end

infosolidario/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def index
  end
end

infosolidario/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recurso = DonacionRecurso.all
  	@producto = Producto.all
  end
end

infosolidario/app/helpers/application_helper.rb
module ApplicationHelper
end

infosolidario/app/helpers/donaciones_helper.rb
module DonacionesHelper
end

infosolidario/app/helpers/lista_helper.rb
module ListaHelper
end

infosolidario/app/helpers/productos_helper.rb
module ProductosHelper
end

infosolidario/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

infosolidario/app/helpers/welcome_helper.rb
module WelcomeHelper
end

infosolidario/app/views/donaciones/index.html.erb
<%@recurso.each do |l| %>
<div class="row">
		<div class="col-sm-4">
			<img src="assets/<%=l.img%>" width="30%" height="30%" class="img-responsive center-block" alt="">
			<%=l.img%>
		</div>	
		<div class="col-sm-4">
			<%=l.description%>
		</div>
		<div class="col-sm-4">
			Creado: <%=l.created_at%> 
		</div>
		<br><br>
</div>
<%end%>

infosolidario/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infosolidario</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<header>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="row">
					<div class="navbar-header col-sm-3">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="#" class="navbar-brand">Raul Calle</a>
					</div>
					<div class="collapse navbar-collapse navbar-right col-sm-7" id="navbar-1">
						<ul class="nav navbar-nav">
							<li id="navbarContact">
								<%= link_to "Donaciones", donaciones_index_path%>
							</li>
							<li id="navbarContact">
								<%= link_to "Productos", productos_index_path%>
							</li>
							<% if donante_signed_in? %>
							<li>
								<%= link_to "Cerrar sesion", destroy_donante_session_path, method: :delete%>
							</li>
							<% else %>
							<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Donante", new_donante_registration_path%>
									</li>
									<li>
										<%= link_to "Empresa", new_empresa_registration_path%>
									</li>
									<li>
										<%= link_to "ONG", new_ong_registration_path%>
									</li>
								</ul>
							</li>
							<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign In<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li>
										<%= link_to "Donante", new_donante_session_path%>
									</li>
									<li>
										<%= link_to "Empresa", new_empresa_session_path%>
									</li>
									<li>
										<%= link_to "ONG", new_ong_session_path%>
									</li>
								</ul>
							</li>
							<%end%>		
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header>
</div>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

infosolidario/app/views/lista/index.html.erb
	<h1>Lista#index</h1>
	<p>Find me in app/views/lista/index.html.erb</p>

infosolidario/app/views/productos/index.html.erb
<%@lista.each do |l| %>
<div class="row">
		<div class="col-sm-4">
			<img src="assets/<%=l.img%>" width="30%" height="30%" class="img-responsive center-block" alt="">
			<%=l.img%>
		</div>	
		<div class="col-sm-4">
			<%=l.description%>
		</div>
		<div class="col-sm-4">
			Creado: <%=l.created_at%> <br>
			Puntos: <%=l.points%>
		</div>
		<br><br>
</div>
<%end%>

infosolidario/app/views/usuarios/index.html.erb
<h1>Usuarios#index</h1>
<p>Find me in app/views/usuarios/index.html.erb</p>

infosolidario/app/views/welcome/index.html.erb
<div class="row text-center">
	<div class="col-sm-3" style="background-color: #fff">
		<h4>Ultimas aportaciones</h4><br>
		<%@producto.each do |l| %>
			
			<img src="assets/<%=l.img%>" width="30%" height="30%" class="img-responsive center-block" alt="">

			<%=l.description%><br>

			Creado: <%=l.created_at%>

			<br>
		<%end%>
	</div>
	<div class="col-sm-6">
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="//www.youtube.com/embed/IibNqwndtCE"></iframe>
		</div>
		<br><br><br><br>
		<div class="row">
			<div class="col-xs-4">
				<img src="assets/1.jpg" class="img-responsive" alt="">
				<img src="assets/2.jpg" class="img-responsive" alt="">
			</div>
			<div class="col-xs-4">
				<img src="assets/3.jpg" class="img-responsive" alt="">
				<img src="assets/4.jpg" class="img-responsive" alt="">
			</div>
			<div class="col-xs-4">
				<img src="assets/5.jpg" class="img-responsive" alt="">
				<img src="assets/6.jpg" class="img-responsive" alt="">
			</div>
		</div>
	</div>
	<div class="col-sm-3">
		
		<h4>Ultimas donaciones</h4><br>
		<%@recurso.each do |l| %>
			
			<img src="assets/<%=l.img%>" width="30%" height="30%" class="img-responsive center-block" alt="">

			<%=l.description%><br>

			Creado: <%=l.created_at%>

			<br>
		<%end%>
	</div>
</div>
<div class="row">
	<img src="assets/footer.png" class="img-responsive" alt="">
</div>